name: UNIX Timestamp Converter
on: [pull_request]
permissions:
  contents: read
jobs:
  gradle_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@v6

      - name: Build and test plugin
        run: ./gradlew clean build

      - name: Execute Plugin Verifier
        run: ./gradlew verifyPlugin
